In [1]:
# imports
import numpy as np

# definiere Funktion zum Erstellen einer DH-Transformationsmatrix
def get_DH_matrix(phi, d, a, alpha):
    # convert from degree to rad
    alpha = 2*np.pi/360*alpha
    phi = 2*np.pi/360*phi
    
    matrix = np.array([
        [np.cos(phi), -1*np.sin(phi)*np.cos(alpha), np.sin(phi)*np.sin(alpha), a*np.cos(phi)],
        [np.sin(phi), np.cos(phi)*np.cos(alpha), -1*np.cos(phi)*np.sin(alpha), a*np.sin(phi)],
        [0, np.sin(alpha), np.cos(alpha), d],
        [0, 0, 0, 1]
    ])
    return matrix

In [2]:
# Festlegung der Denavit-Hartenberg Parameter
gelenke = 2 # nur Gelenke angeben, die selber definiert worden sind
DH_Parameter = [i for i in range(gelenke)]
for i in range(gelenke):
    print('Eingabe Gelenk ' + str(i+1) + ':')
    DH_Parameter[i] = {'phi': float(input('Phi:')), 
                       'd': float(input('d: ')), 
                       'a': float(input('a: ')), 
                       'alpha': float(input('alpha: ')) }
    

Eingabe Gelenk 1:


Phi: 0
d:  0
a:  0
alpha:  -90


Eingabe Gelenk 2:


Phi: 0
d:  85
a:  0
alpha:  0


In [3]:
# Festlegung ob vorherige Gelenke bereits definiert sind
if_previous = True

if if_previous:
    print('Input Matrix')
    input_matrix = np.array([
        [0, 0, 1, 0],
        [0, -1, 0, -1405.5],
        [1, 0, 0, 1765],
        [0, 0, 0, 1]
    ])
else:
    print('Use no previously defined matrix')
    input_matrix = np.eye(4)

DH_matrizen = [i for i in range(gelenke+1)]
DH_matrizen[0] = input_matrix

for i in range(gelenke):
    matrix = np.round(get_DH_matrix(**DH_Parameter[i]), 10)
    print(matrix)
    DH_matrizen[i+1] = matrix

Input Matrix
[[ 1. -0. -0.  0.]
 [ 0.  0.  1.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0.  0.  1.]]
[[ 1. -0.  0.  0.]
 [ 0.  1. -0.  0.]
 [ 0.  0.  1. 85.]
 [ 0.  0.  0.  1.]]


In [6]:
final_matrix = np.eye(4)
for i in range(gelenke+1):
    final_matrix = np.round(final_matrix @ DH_matrizen[i], 5)
    
print(final_matrix)

[[ 0.0000e+00 -1.0000e+00  0.0000e+00  0.0000e+00]
 [ 0.0000e+00  0.0000e+00 -1.0000e+00 -1.4905e+03]
 [ 1.0000e+00  0.0000e+00  0.0000e+00  1.7650e+03]
 [ 0.0000e+00  0.0000e+00  0.0000e+00  1.0000e+00]]
